### PR TITLE
Fix Pcre.split

### LINKED ISSUE #288: Behavior or Re.Pcre.split when only separators are found
I observe this behavior (Debian Sid, re 1.11.0):

```
utop # let whitespace_re = Re.Pcre.regexp "\\s+";;
val whitespace_re : Re.re = <abstr>

utop # Re.Pcre.split ~rex:whitespace_re ("");;
- : string list = []

utop # Re.Pcre.split ~rex:whitespace_re (" ");;
- : string list = [""]
```

Is it the expected behavior? In the second case I would have expected `[]` instead of `[""]`.

For comparison, here's what I get with the `pcre` library:

```
utop # Pcre.split ("");;
- : string list = []

utop # Pcre.split ("  ");;
- : string list = []
```

Thanks

### LINKED ISSUE #411: re 1.12 broke tests in a dose3
All tests associated with comparing versions through semver in dose3-7.0.0 are breaking.
I think that arrays are incorrectly filled when analyzing the version by regular expression.

With ocaml-re 1.11 everything works fine.

And with ocaml-re 1.12:
FAILED: Cases: 112 Tried: 112 Errors: 0 Failures: 21 Skip:  0 Todo: 0 Timeouts: 0.

One example of the output from the list of broken tests:

Failure: suite:5:test_decompose:5: =1.2.3
expected: 1.2.3-+ but got: 1.2.3

part of the src/versioning/semverNode.ml from dose3:
```
let rex =
  Pcre.regexp
    ("^\\s*[v=]*\\s*"
   (* optional version identifier *)
   ^ "([0-9]+|[xX*])(\\.([0-9]+|[xX*])?(\\.([0-9]+|[xX*])?)?)?"
    (* 3-dotted notation *)
    ^ "(?:-((?:[a-zA-Z0-9]+|[a-zA-Z0-9-])(?:\\.[a-zA-Z0-9]+|[a-zA-Z0-9-])*))?"
    ^ (* pre release *)
    "(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?\\s*$" (* build indentifier *)
    )

let sep_re = Pcre.regexp "\\."

let parse_raw_version version =
  try
    let parsed = Pcre.extract ~rex version in
    let pre = Pcre.split ~rex:sep_re parsed.(6) in
    let build = Pcre.split ~rex:sep_re parsed.(7) in
    (parsed.(1), parsed.(3), parsed.(5), pre, build)
  with Not_found ->
    raise
      (Invalid_argument
         (Printf.sprintf "%s: Parsing Error. Invalid Version" version))
```

### PR DESCRIPTION
**Pull request by vouillon**
An occurrence of the delimiter at the beginning or at the end of the string is ignored.

Fixes #288, fixes #411.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]

**Comment by rgrinberg** [comment]
Thanks. A changes entry is warranted.

File: lib_test/expect/test_pcre_split.ml [hunk 1]
```diff
@@ -4,20 +4,20 @@ let split ~rex s = Re.Pcre.split ~rex s |> strings
 
 let%expect_test "split" =
   split ~rex:re_whitespace "aa bb c d ";
-  [%expect {| ["aa"; "bb"; "c"; "d"; ""] |}];
+  [%expect {| ["d"; "c"; "bb"; "aa"] |}];
```
Comment (glittershark) [inline lib_test/expect/test_pcre_split.ml:7]: I think this is wrong; the output is reversed here, but not if the delimiter is present at the beginning of the string (eg in other test cases)
